# Generated by Django 3.2.25 on 2024-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=254)),
                ('vehicle_reg_number', models.CharField(max_length=20)),
            ],
        ),
    ]
